package com.trading.bot.monitoring;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents a trading call generated by the system
 */
public class GeneratedCall {
    
    private final String callId;
    private final String symbol;
    private final String callType; // CE, PE, Equity
    private final String expectedDirection; // BULLISH, BEARISH
    private final double entryPrice;
    private final double targetPrice;
    private final double stopLossPrice;
    private final double investmentAmount;
    private final double confidence;
    private final String strategy;
    private final String rationale;
    private final LocalDateTime generatedTime;
    private final LocalDateTime expiryTime;
    
    // Builder pattern for easy construction
    public static class Builder {
        private String callId = UUID.randomUUID().toString();
        private String symbol;
        private String callType = "CE";
        private String expectedDirection = "BULLISH";
        private double entryPrice;
        private double targetPrice;
        private double stopLossPrice;
        private double investmentAmount = 10000.0;
        private double confidence = 0.75;
        private String strategy = "Long Call";
        private String rationale = "Technical analysis";
        private LocalDateTime generatedTime = LocalDateTime.now();
        private LocalDateTime expiryTime;
        
        public Builder symbol(String symbol) {
            this.symbol = symbol;
            return this;
        }
        
        public Builder callType(String callType) {
            this.callType = callType;
            return this;
        }
        
        public Builder expectedDirection(String expectedDirection) {
            this.expectedDirection = expectedDirection;
            return this;
        }
        
        public Builder entryPrice(double entryPrice) {
            this.entryPrice = entryPrice;
            return this;
        }
        
        public Builder targetPrice(double targetPrice) {
            this.targetPrice = targetPrice;
            return this;
        }
        
        public Builder stopLossPrice(double stopLossPrice) {
            this.stopLossPrice = stopLossPrice;
            return this;
        }
        
        public Builder investmentAmount(double investmentAmount) {
            this.investmentAmount = investmentAmount;
            return this;
        }
        
        public Builder confidence(double confidence) {
            this.confidence = confidence;
            return this;
        }
        
        public Builder strategy(String strategy) {
            this.strategy = strategy;
            return this;
        }
        
        public Builder rationale(String rationale) {
            this.rationale = rationale;
            return this;
        }
        
        public Builder expiryTime(LocalDateTime expiryTime) {
            this.expiryTime = expiryTime;
            return this;
        }
        
        public GeneratedCall build() {
            if (symbol == null || symbol.trim().isEmpty()) {
                throw new IllegalArgumentException("Symbol is required");
            }
            if (entryPrice <= 0) {
                throw new IllegalArgumentException("Entry price must be positive");
            }
            if (targetPrice <= 0) {
                throw new IllegalArgumentException("Target price must be positive");
            }
            
            return new GeneratedCall(this);
        }
    }
    
    private GeneratedCall(Builder builder) {
        this.callId = builder.callId;
        this.symbol = builder.symbol;
        this.callType = builder.callType;
        this.expectedDirection = builder.expectedDirection;
        this.entryPrice = builder.entryPrice;
        this.targetPrice = builder.targetPrice;
        this.stopLossPrice = builder.stopLossPrice;
        this.investmentAmount = builder.investmentAmount;
        this.confidence = builder.confidence;
        this.strategy = builder.strategy;
        this.rationale = builder.rationale;
        this.generatedTime = builder.generatedTime;
        this.expiryTime = builder.expiryTime;
    }
    
    // Static factory method
    public static Builder builder() {
        return new Builder();
    }
    
    // Convenience constructor for quick creation
    public GeneratedCall(String symbol, String callType, String expectedDirection,
                        double entryPrice, double targetPrice, double investmentAmount) {
        this.callId = UUID.randomUUID().toString();
        this.symbol = symbol;
        this.callType = callType;
        this.expectedDirection = expectedDirection;
        this.entryPrice = entryPrice;
        this.targetPrice = targetPrice;
        this.stopLossPrice = entryPrice * (expectedDirection.equals("BULLISH") ? 0.95 : 1.05);
        this.investmentAmount = investmentAmount;
        this.confidence = 0.75;
        this.strategy = callType.contains("CE") ? "Long Call" : "Long Put";
        this.rationale = "Technical analysis based";
        this.generatedTime = LocalDateTime.now();
        this.expiryTime = LocalDateTime.now().plusDays(7); // Weekly expiry
    }
    
    // Getters
    public String getCallId() { return callId; }
    public String getSymbol() { return symbol; }
    public String getCallType() { return callType; }
    public String getExpectedDirection() { return expectedDirection; }
    public double getEntryPrice() { return entryPrice; }
    public double getTargetPrice() { return targetPrice; }
    public double getStopLossPrice() { return stopLossPrice; }
    public double getInvestmentAmount() { return investmentAmount; }
    public double getConfidence() { return confidence; }
    public String getStrategy() { return strategy; }
    public String getRationale() { return rationale; }
    public LocalDateTime getGeneratedTime() { return generatedTime; }
    public LocalDateTime getExpiryTime() { return expiryTime; }
    
    @Override
    public String toString() {
        return String.format("GeneratedCall[%s: %s %s %s @ ₹%.2f → ₹%.2f, Confidence: %.1f%%]",
            callId.substring(0, 8), symbol, strategy, expectedDirection, 
            entryPrice, targetPrice, confidence * 100);
    }
    
    public String getDetailedString() {
        return String.format(
            "Call ID: %s\n" +
            "Symbol: %s\n" +
            "Type: %s (%s)\n" +
            "Direction: %s\n" +
            "Entry: ₹%.2f\n" +
            "Target: ₹%.2f\n" +
            "Stop Loss: ₹%.2f\n" +
            "Investment: ₹%.2f\n" +
            "Confidence: %.1f%%\n" +
            "Strategy: %s\n" +
            "Rationale: %s\n" +
            "Generated: %s\n" +
            "Expiry: %s",
            callId,
            symbol,
            callType,
            strategy,
            expectedDirection,
            entryPrice,
            targetPrice,
            stopLossPrice,
            investmentAmount,
            confidence * 100,
            strategy,
            rationale,
            generatedTime.toString(),
            expiryTime != null ? expiryTime.toString() : "N/A"
        );
    }
}