services:
  - type: worker
    name: option-analyzer-bot
    env: docker
    plan: free
    region: singapore
    branch: OptionMaster
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: UPSTOX_API_KEY
        sync: false
      - key: UPSTOX_API_SECRET
        sync: false
      - key: UPSTOX_ACCESS_TOKEN
        sync: false
