#!/bin/bash

echo "🎯 === BOT BACKTEST FOR OCTOBER 31ST, 2025 ====="
echo "📊 Testing bot performance with official BSE/NSE market data"
echo "🤖 Analyzing call generation accuracy and statistics"
echo ""

cd "$(dirname "$0")"

echo "🔧 Compiling backtest system..."
javac -d "target/classes" "src/main/java/com/trading/bot/backtest/BotBacktestOct31_2025.java"

if [ $? -eq 0 ]; then
    echo "✅ Compilation successful!"
    echo ""
    
    echo "🚀 Starting comprehensive backtest for October 31st, 2025..."
    echo "📅 Test Date: 31-Oct-2025 (Friday)"
    echo "📊 Data Sources: Official BSE & NSE market data"
    echo "🎯 Analysis: Call generation, accuracy, performance metrics"
    echo ""
    echo "=" | head -c 70; echo ""
    
    # Run the comprehensive backtest
    java -cp "target/classes" com.trading.bot.backtest.BotBacktestOct31_2025
    
    echo "=" | head -c 70; echo ""
    echo ""
    echo "🎉 === BACKTEST ANALYSIS COMPLETED ====="
    echo ""
    echo "📋 BACKTEST SUMMARY:"
    echo "   ✅ Market data fetched from BSE & NSE"
    echo "   ✅ Bot algorithms tested on historical data"
    echo "   ✅ Call generation statistics calculated"
    echo "   ✅ Accuracy metrics computed"
    echo "   ✅ Performance analysis completed"
    echo ""
    echo "💡 KEY INSIGHTS AVAILABLE:"
    echo "   📊 Total calls generated by your bot"
    echo "   🎯 Accuracy percentage achieved"
    echo "   ⏰ Performance by time of day"
    echo "   📈 Best performing indices"
    echo "   🏆 Top strategy setups"
    echo "   💡 Optimization recommendations"
    echo ""
    echo "🚀 Use these insights to enhance your bot's performance!"
    
else
    echo "❌ Compilation failed"
    echo "Please check Java installation and try again"
fi