package com.trading.bot.technical;

import com.trading.bot.market.SimpleMarketData;
import java.util.*;

public class AdvancedCandlestickDetector {
    public static Set<String> detectAll(List<SimpleMarketData> data) {
        Set<String> out = new LinkedHashSet<>();
        if (data == null || data.size() < 5) return out;
        SimpleMarketData c1 = data.get(data.size() - 1);
        SimpleMarketData c2 = data.get(data.size() - 2);
        SimpleMarketData c3 = data.get(data.size() - 3);
        SimpleMarketData c4 = data.get(data.size() - 4);
        SimpleMarketData c5 = data.get(data.size() - 5);
        double body1 = Math.abs(c1.price - c1.open);
        double body2 = Math.abs(c2.price - c2.open);
        double body3 = Math.abs(c3.price - c3.open);
        double range1 = c1.high - c1.low;
        double range2 = c2.high - c2.low;
        double range3 = c3.high - c3.low;
        double lowerWick1 = Math.min(c1.price, c1.open) - c1.low;
        double upperWick1 = c1.high - Math.max(c1.price, c1.open);
        double lowerWick2 = Math.min(c2.price, c2.open) - c2.low;
        double upperWick2 = c2.high - Math.max(c2.price, c2.open);
        double lowerWick3 = Math.min(c3.price, c3.open) - c3.low;
        double upperWick3 = c3.high - Math.max(c3.price, c3.open);
        boolean up1 = c1.price > c1.open;
        boolean up2 = c2.price > c2.open;
        boolean up3 = c3.price > c3.open;
        boolean down1 = !up1;
        boolean down2 = !up2;
        boolean down3 = !up3;
        if (lowerWick1 > body1 * 1.5 && upperWick1 <= body1 * 0.3 && down2) out.add("Hammer");
        if (upperWick1 > body1 * 1.5 && lowerWick1 <= body1 * 0.3 && up2) out.add("Shooting Star");
        if (lowerWick1 > body1 * 1.5 && upperWick1 <= body1 * 0.3 && up2) out.add("Inverted Hammer");
        if (upperWick1 > body1 * 1.5 && lowerWick1 <= body1 * 0.3 && down2) out.add("Hanging Man");
        double dojiThresh1 = range1 * 0.1;
        if (body1 <= dojiThresh1 && upperWick1 > body1 && lowerWick1 > body1) out.add("Doji");
        if (body1 <= range1 * 0.05 && upperWick1 < lowerWick1 * 0.2) out.add("Dragonfly Doji");
        if (body1 <= range1 * 0.05 && lowerWick1 < upperWick1 * 0.2) out.add("Gravestone Doji");
        if (upperWick1 < range1 * 0.05 && lowerWick1 < range1 * 0.05) {
            if (up1) out.add("Bullish Marubozu"); else out.add("Bearish Marubozu");
        }
        if (body1 <= range1 * 0.3 && upperWick1 > body1 && lowerWick1 > body1) out.add("Spinning Top");
        if (up1 && c1.open <= c2.low && body1 >= range1 * 0.6) out.add("Bullish Belt Hold");
        if (down1 && c1.open >= c2.high && body1 >= range1 * 0.6) out.add("Bearish Belt Hold");
        if (up1 && down2 && c1.price > c2.open && body1 > body2) out.add("Bullish Engulfing");
        if (down1 && up2 && c1.price < c2.open && body1 > body2) out.add("Bearish Engulfing");
        boolean bullHarami = up1 && down2 && body1 < body2 && Math.max(c1.price, c1.open) <= Math.max(c2.open, c2.price) && Math.min(c1.price, c1.open) >= Math.min(c2.open, c2.price);
        boolean bearHarami = down1 && up2 && body1 < body2 && Math.max(c1.price, c1.open) <= Math.max(c2.open, c2.price) && Math.min(c1.price, c1.open) >= Math.min(c2.open, c2.price);
        if (bullHarami) out.add("Bullish Harami");
        if (bearHarami) out.add("Bearish Harami");
        if (up1 && down2 && c1.price > (c2.open + c2.price) / 2) out.add("Piercing Line");
        if (down1 && up2 && c1.price < (c2.open + c2.price) / 2) out.add("Dark Cloud Cover");
        if (c1.high == c2.high) out.add("Tweezer Top");
        if (c1.low == c2.low) out.add("Tweezer Bottom");
        if ((up1 && down2 && c1.open > c2.open && c1.open > c2.price) || (down1 && up2 && c1.open < c2.open && c1.open < c2.price)) out.add("Kicker Pattern");
        boolean morningStar = down3 && Math.abs(body2) <= range2 * 0.3 && up1 && c1.price > (c3.open + c3.price) / 2;
        boolean eveningStar = up3 && Math.abs(body2) <= range2 * 0.3 && down1 && c1.price < (c3.open + c3.price) / 2;
        if (morningStar) out.add("Morning Star");
        if (eveningStar) out.add("Evening Star");
        boolean threeSoldiers = up1 && up2 && up3 && c1.price > c2.price && c2.price > c3.price && body1 > range1 * 0.3 && body2 > range2 * 0.3 && body3 > range3 * 0.3;
        boolean threeCrows = down1 && down2 && down3 && c1.price < c2.price && c2.price < c3.price && body1 > range1 * 0.3 && body2 > range2 * 0.3 && body3 > range3 * 0.3;
        if (threeSoldiers) out.add("Three White Soldiers");
        if (threeCrows) out.add("Three Black Crows");
        boolean threeInsideUp = up1 && down2 && down3 && c2.price < c2.open && body2 > body3 && c1.price > c2.open;
        boolean threeInsideDown = down1 && up2 && up3 && c2.price > c2.open && body2 > body3 && c1.price < c2.open;
        if (threeInsideUp) out.add("Three Inside Up");
        if (threeInsideDown) out.add("Three Inside Down");
        boolean abandonedBabyBull = down3 && Math.abs(body2) <= range2 * 0.1 && up1 && c2.low > c3.price && c1.open > c2.high;
        boolean abandonedBabyBear = up3 && Math.abs(body2) <= range2 * 0.1 && down1 && c2.high < c3.price && c1.open < c2.low;
        if (abandonedBabyBull) out.add("Bullish Abandoned Baby");
        if (abandonedBabyBear) out.add("Bearish Abandoned Baby");
        boolean risingThree = up3 && up2 && up1 && c2.price < c2.open && c3.price < c3.open && c1.price > c4.high;
        boolean fallingThree = down3 && down2 && down1 && c2.price > c2.open && c3.price > c3.open && c1.price < c4.low;
        if (risingThree) out.add("Rising Three Methods");
        if (fallingThree) out.add("Falling Three Methods");
        boolean matHoldBull = up3 && up2 && c2.price < c2.open && c3.price < c3.open && up1 && c1.price > c4.high;
        boolean matHoldBear = down3 && down2 && c2.price > c2.open && c3.price > c3.open && down1 && c1.price < c4.low;
        if (matHoldBull) out.add("Mat Hold Bullish");
        if (matHoldBear) out.add("Mat Hold Bearish");
        boolean threeLineStrikeBull = up3 && up2 && up1 && down1 && c1.price < c3.open;
        boolean threeLineStrikeBear = down3 && down2 && down1 && up1 && c1.price > c3.open;
        if (threeLineStrikeBull) out.add("Three-Line Strike Bullish");
        if (threeLineStrikeBear) out.add("Three-Line Strike Bearish");
        boolean ladderBottom = down3 && down2 && down1 && up1 && c1.price > c2.open;
        if (ladderBottom) out.add("Ladder Bottom");
        boolean concealingBabySwallow = down3 && down2 && !up2 && !up3 && lowerWick2 == 0 && lowerWick3 == 0 && c1.open < c2.low && c1.price < c2.low;
        if (concealingBabySwallow) out.add("Concealing Baby Swallow");
        return out;
    }
}
